replicaCount: 2

image:
  repository: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_REGION>.amazonaws.com/profile-service
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3002

resources: {}
